https://www.kaggle.com/rtatman/188-million-us-wildfires

https://www.fs.usda.gov/rds/archive/Product/RDS-2013-0009.4/

## Prepare Notebook

In [1]:
import os
import pandas as pd
from geopandas import GeoDataFrame
import shapely
shapely.speedups.enable()

import palettable

import mapbox
import palettable

import sqlite3

import warnings
warnings.filterwarnings('ignore')

import fiona
fiona.supported_drivers

input_filename = '../data/188-million-us-wildfires/src/FPA_FOD_20170508.sqlite'
conn = sqlite3.connect(input_filename)

The whole process of bringing the data into a DataFrame, converting that into a GeoDataFrame, and then dumping out a file is not particularly optimal. That said, it may prove to be useful if we choose to engineer any new features before rendering the map.

The data we're working with contains coordinates in the [NAD83](https://en.wikipedia.org/wiki/North_American_Datum) coordinate system. In order to work with `tippecanoe` we will want to reproject the data into [WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System).

Let's take a quick peek at our data to ensure it look's reasonable.

## Load Data

In [2]:
query = '''
    SELECT
        NWCG_REPORTING_AGENCY,
        NWCG_REPORTING_UNIT_ID,
        NWCG_REPORTING_UNIT_NAME,
        FIRE_NAME,
        COMPLEX_NAME,
        FIRE_YEAR,
        DISCOVERY_DATE,
        DISCOVERY_DOY,
        DISCOVERY_TIME,
        STAT_CAUSE_CODE,
        STAT_CAUSE_DESCR,
        CONT_DATE,
        CONT_DOY,
        CONT_TIME,
        FIRE_SIZE,
        FIRE_SIZE_CLASS,
        LATITUDE,
        LONGITUDE,
        OWNER_CODE,
        OWNER_DESCR,
        STATE,
        COUNTY
    FROM
        Fires;
'''

df = pd.read_sql_query(query, conn)
geometry = [shapely.geometry.Point(xy) for xy in zip(df.LONGITUDE, df.LATITUDE)]
df.drop(['LONGITUDE', 'LATITUDE'], axis=1, inplace=True)
crs = {'init': 'epsg:4269'}
gdf = GeoDataFrame(df, crs=crs, geometry=geometry)
del df
gdf = gdf.to_crs({'init': 'epsg:4326'})

### Checkpoint

Getting `gdf` to the state it is right now took some time. Let's checkpoint the file onto disk so we can come back to it later.

In [9]:
gdf_checkpoint_path = '../data/188-million-us-wildfires/wildfiles-to-geojson-gdf_checkpoint_0.pickle'

OVERWRITE = False

if not os.path.exists(gdf_checkpoint_path) or OVERWRITE:
    gdf.to_pickle(gdf_checkpoint_path)
else :
    gdf = pd.read_pickle(gdf_checkpoint_path)

## Characterize Data

In [11]:
print(gdf.info())
gdf.sample(5)

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1880465 entries, 0 to 1880464
Data columns (total 21 columns):
NWCG_REPORTING_AGENCY       object
NWCG_REPORTING_UNIT_ID      object
NWCG_REPORTING_UNIT_NAME    object
FIRE_NAME                   object
COMPLEX_NAME                object
FIRE_YEAR                   int64
DISCOVERY_DATE              float64
DISCOVERY_DOY               int64
DISCOVERY_TIME              object
STAT_CAUSE_CODE             float64
STAT_CAUSE_DESCR            object
CONT_DATE                   float64
CONT_DOY                    float64
CONT_TIME                   object
FIRE_SIZE                   float64
FIRE_SIZE_CLASS             object
OWNER_CODE                  float64
OWNER_DESCR                 object
STATE                       object
COUNTY                      object
geometry                    object
dtypes: float64(6), int64(2), object(13)
memory usage: 301.3+ MB
None

,NWCG_REPORTING_AGENCY,NWCG_REPORTING_UNIT_ID,NWCG_REPORTING_UNIT_NAME,FIRE_NAME,COMPLEX_NAME,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,...,CONT_DATE,CONT_DOY,CONT_TIME,FIRE_SIZE,FIRE_SIZE_CLASS,OWNER_CODE,OWNER_DESCR,STATE,COUNTY,geometry
1161049,ST/C&L,USALALS,Alabama Forestry Commission,None,None,2006,2453802.5,67,2357,2.0,...,2453802.5,67.0,None,3.00,B,14.0,MISSING/NOT SPECIFIED,AL,Clarke,POINT (-87.710069 31.968901)
1473185,ST/C&L,USSCSCS,South Carolina Forestry Commission,None,None,2011,2455610.5,49,1259,2.0,...,2455610.5,49.0,1610,8.00,B,8.0,PRIVATE,SC,Williamsburg County,POINT (-79.756004 33.494862)
837420,ST/C&L,USALALS,Alabama Forestry Commission,None,None,1997,2450504.5,56,None,7.0,...,NaN,NaN,None,1.50,B,14.0,MISSING/NOT SPECIFIED,AL,None,POINT (-87.2381 34.5981)
1848660,ST/C&L,USKSKSS,Kansas State Forestry,3790,None,2015,2457333.5,311,None,9.0,...,2457333.5,311.0,None,0.01,A,14.0,MISSING/NOT SPECIFIED,KS,Reno,POINT (-97.84999999999999 38.07)
1316133,ST/C&L,USWVWVS,West Virginia Division of Forestry,ALMA,None,2003,2452723.5,84,1302,5.0,...,2452723.5,84.0,1302,0.20,A,8.0,PRIVATE,WV,Tyler,POINT (-80.83850379 39.42600509)

### Missing Data

Let's begin to understand what data is missing and what we can do about it.

In [12]:
gdf.isnull().sum()

NWCG_REPORTING_AGENCY             0
NWCG_REPORTING_UNIT_ID            0
NWCG_REPORTING_UNIT_NAME          0
FIRE_NAME                    957189
COMPLEX_NAME                1875282
FIRE_YEAR                         0
DISCOVERY_DATE                    0
DISCOVERY_DOY                     0
DISCOVERY_TIME               882638
STAT_CAUSE_CODE                   0
STAT_CAUSE_DESCR                  0
CONT_DATE                    891531
CONT_DOY                     891531
CONT_TIME                    972173
FIRE_SIZE                         0
FIRE_SIZE_CLASS                   0
OWNER_CODE                        0
OWNER_DESCR                       0
STATE                             0
COUNTY                       678148
geometry                          0
dtype: int64

#### Date Bounds

Get earliest and latest dates of fires. File this away for use building a visualization later on. Keep in mind that the dates are formatted as [Julian Dates](https://en.wikipedia.org/wiki/Julian_day) in the database - this makes working with the date fairly easy, but we have to remember to convert back to a readable format for visualization.

In [13]:
print('Earliest Discovery Date: {}'.format(gdf.DISCOVERY_DATE.min()))
print('Latest Discovery Date: {}'.format(gdf.DISCOVERY_DATE.max()))
print('Earliest Contained Date: {}'.format(gdf.CONT_DATE.min()))
print('Latest Contained Date: {}'.format(gdf.CONT_DATE.max()))

Earliest Discovery Date: 2448622.5
Latest Discovery Date: 2457387.5
Earliest Contained Date: 2448622.5
Latest Contained Date: 2457391.5

## Data Engineering

#### TODO
- synthesize 'duration'

### GeoHash

We will add a GeoHash to each row in the DF. This will allow us to perform aggregations on a consistent and queryable grid.

Reference: https://en.wikipedia.org/wiki/Geohash

In [39]:
import geohash

def geohashes_for_geometry(geometry, precision=[7, 6, 4, 3]):
    _lon = geometry.coords.xy[0][0]
    _lat = geometry.coords.xy[1][0]
    _geohash = geohash.encode(_lat, _lon, precision=precision[0])
    _output = [_geohash[0:p] for p in precision]
    return pd.Series(_output)


geohashes = gdf['geometry'].apply(geohashes_for_geometry, precision=[4])
geohashes = geohashes.rename(columns={0: 'geohash_5'})

In [29]:
gdf = gdf.join(geohashes)

In [31]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1880465 entries, 0 to 1880464
Data columns (total 23 columns):
NWCG_REPORTING_AGENCY       object
NWCG_REPORTING_UNIT_ID      object
NWCG_REPORTING_UNIT_NAME    object
FIRE_NAME                   object
COMPLEX_NAME                object
FIRE_YEAR                   int64
DISCOVERY_DATE              float64
DISCOVERY_DOY               int64
DISCOVERY_TIME              object
STAT_CAUSE_CODE             float64
STAT_CAUSE_DESCR            object
CONT_DATE                   float64
CONT_DOY                    float64
CONT_TIME                   object
FIRE_SIZE                   float64
FIRE_SIZE_CLASS             object
OWNER_CODE                  float64
OWNER_DESCR                 object
STATE                       object
COUNTY                      object
geometry                    object
geohash_6                   object
geohash_5                   object
dtypes: float64(6), int64(2), object(15)
memory usage: 330.0+ MB

In [32]:
gdf.sample(3)

,NWCG_REPORTING_AGENCY,NWCG_REPORTING_UNIT_ID,NWCG_REPORTING_UNIT_NAME,FIRE_NAME,COMPLEX_NAME,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,...,CONT_TIME,FIRE_SIZE,FIRE_SIZE_CLASS,OWNER_CODE,OWNER_DESCR,STATE,COUNTY,geometry,geohash_6,geohash_5
329813,BLM,USIDTFD,Twin Falls District,PICABO,None,2002,2452462.5,188,1430,1.0,...,2030,15.00,C,1.0,BLM,ID,Blaine,POINT (-114.1061 43.2621),9rwy57,9rwy5
1380679,ST/C&L,USGAGAS,Georgia Forestry Commission,None,None,1992,2448698.5,77,1400,2.0,...,1714,5.51,B,8.0,PRIVATE,GA,Richmond,POINT (-82.133 33.2808),djvt74,djvt7
447989,ST/C&L,USGAGAS,Georgia Forestry Commission,None,None,2007,2454185.5,85,None,8.0,...,None,0.25,A,14.0,MISSING/NOT SPECIFIED,GA,Coweta,POINT (-84.83103069000001 33.32033434),djgtt9,djgtt
166626,FS,USOROCF,Ochoco National Forest,0991,None,2004,2453233.5,229,0800,1.0,...,1530,0.10,A,5.0,USFS,OR,None,POINT (-120.60333333 44.55444444),9rfjrw,9rfjr
381435,ST/C&L,USARARS,Arkansas Forestry Commission,None,None,2006,2453737.5,2,None,5.0,...,None,2.00,B,14.0,MISSING/NOT SPECIFIED,AR,Saline,POINT (-92.36715997 34.58832998),9ynkf0,9ynkf
1338696,ST/C&L,USNYNYX,Fire Department of New York,None,None,2005,2453542.5,172,2144,9.0,...,2144,0.10,A,14.0,MISSING/NOT SPECIFIED,NY,RICHMOND,POINT (-74.16370055 40.57618713),dr5qb6,dr5qb
1863533,ST/C&L,USHICNTY,Hawaii Counties,None,None,2007,2454403.5,303,None,13.0,...,None,0.20,A,14.0,MISSING/NOT SPECIFIED,HI,Oahu,POINT (-158.2277069 21.5286751),87z6rr,87z6r
1011529,ST/C&L,USNCNCS,North Carolina Forest Service,None,None,1994,2449387.5,35,None,9.0,...,None,0.10,A,14.0,MISSING/NOT SPECIFIED,NC,None,POINT (-81.14830000000001 36.565),dnw212,dnw21
1686584,ST/C&L,USGAGAS,Georgia Forestry Commission,FY2013-STEWART-024,None,2013,2456390.5,98,1519,5.0,...,1619,1.45,B,8.0,PRIVATE,GA,Stewart,POINT (-84.71410833 32.02896389),djey0q,djey0
1376107,ST/C&L,USGAGAS,Georgia Forestry Commission,None,None,1997,2450670.5,222,1000,1.0,...,2040,18.85,C,8.0,PRIVATE,GA,Telfair,POINT (-82.86109999999999 31.9783),djtjfm,djtjf

### Checkpoint

In [19]:
gdf_checkpoint_path = '../data/188-million-us-wildfires/gdf_checkpoint_1.pickle'

OVERWRITE = False

if not os.path.exists(gdf_checkpoint_path) or OVERWRITE:
    gdf.to_pickle(gdf_checkpoint_path)
else :
    gdf = pd.read_pickle(gdf_checkpoint_path)

## Exploratory Analysis

### GeoHash

#### Precision 3

In [34]:
geohash_analysis_precision = 5

In [35]:
geohash_df = gdf\
    .groupby(['geohash_{}'.format(geohash_analysis_precision), 'FIRE_YEAR'])\
    .size()\
    .unstack()\
    .fillna(value=0)
geohash_df['total'] = geohash_df.sum(axis=1)
geohash_df.sample(3)

FIRE_YEAR,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,total
geohash_5,,,,,,,,,,,,,,,,,,,,,
87ykv,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,1.0,2.0,4.0,1.0,1.0,0.0,0.0,0.0,17.0
87ykx,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,2.0,1.0,0.0,2.0,0.0,0.0,0.0,8.0
87yky,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,16.0,5.0,6.0,11.0,6.0,0.0,0.0,0.0,69.0
87ykz,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,6.0
87ymh,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
87ymj,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,1.0,8.0,2.0,3.0,1.0,0.0,0.0,0.0,27.0
87ymk,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4.0
87ymn,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,5.0
87ymq,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,9.0
87ymr,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

<class 'pandas.core.frame.DataFrame'>
Index: 235624 entries, 87ykv to f8052
Data columns (total 25 columns):
1992     235624 non-null float64
1993     235624 non-null float64
1994     235624 non-null float64
1995     235624 non-null float64
1996     235624 non-null float64
1997     235624 non-null float64
1998     235624 non-null float64
1999     235624 non-null float64
2000     235624 non-null float64
2001     235624 non-null float64
2002     235624 non-null float64
2003     235624 non-null float64
2004     235624 non-null float64
2005     235624 non-null float64
2006     235624 non-null float64
2007     235624 non-null float64
2008     235624 non-null float64
2009     235624 non-null float64
2010     235624 non-null float64
2011     235624 non-null float64
2012     235624 non-null float64
2013     235624 non-null float64
2014     235624 non-null float64
2015     235624 non-null float64
total    235624 non-null float64
dtypes: float64(25)
memory usage: 46.7+ MB

None

In [36]:
def geohash_to_polygon(row):
    _coords = geohash.decode(row.name, delta=True)
    _x = _coords[1]
    _y = _coords[0]
    _xd = _coords[3]
    _yd = _coords[2]
    _poly = shapely.geometry.box(
        _x - _xd,
        _y - _yd,
        _x + _xd,
        _y + _yd,
    )
    return _poly
    
geometry = geohash_df.apply(geohash_to_polygon, axis=1).tolist()
geometry[0:10]

[<shapely.geometry.polygon.Polygon at 0x7fe34d5908d0>,
 <shapely.geometry.polygon.Polygon at 0x7fe34d5c1048>,
 <shapely.geometry.polygon.Polygon at 0x7fe34d362e10>,
 <shapely.geometry.polygon.Polygon at 0x7fe34d362eb8>,
 <shapely.geometry.polygon.Polygon at 0x7fe34d362780>,
 <shapely.geometry.polygon.Polygon at 0x7fe34d362630>,
 <shapely.geometry.polygon.Polygon at 0x7fe34d362198>,
 <shapely.geometry.polygon.Polygon at 0x7fe34d3620f0>,
 <shapely.geometry.polygon.Polygon at 0x7fe34d362390>,
 <shapely.geometry.polygon.Polygon at 0x7fe34d362588>]

In [37]:
geohash_df.index = geohash_df.index.map(str)
geohash_df.columns = geohash_df.columns.map(str)
geohash_gdf = GeoDataFrame(geohash_df, geometry=geometry)
del geohash_df
geohash_gdf.sample(3)

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 235624 entries, 87ykv to f8052
Data columns (total 26 columns):
1992        235624 non-null float64
1993        235624 non-null float64
1994        235624 non-null float64
1995        235624 non-null float64
1996        235624 non-null float64
1997        235624 non-null float64
1998        235624 non-null float64
1999        235624 non-null float64
2000        235624 non-null float64
2001        235624 non-null float64
2002        235624 non-null float64
2003        235624 non-null float64
2004        235624 non-null float64
2005        235624 non-null float64
2006        235624 non-null float64
2007        235624 non-null float64
2008        235624 non-null float64
2009        235624 non-null float64
2010        235624 non-null float64
2011        235624 non-null float64
2012        235624 non-null float64
2013        235624 non-null float64
2014        235624 non-null float64
2015        235624 non-null float64
total       235624 non-null float64
geometry    235624 non-null object
dtypes: float64(25), object(1)
memory usage: 48.5+ MB

FIRE_YEAR,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,...,2008,2009,2010,2011,2012,2013,2014,2015,total,geometry
geohash_5,,,,,,,,,,,,,,,,,,,,,
9vsn5,2.0,1.0,0.0,1.0,2.0,0.0,0.0,1.0,2.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,"POLYGON ((-95.44921875 31.9921875, -95.4492187..."
c80md,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,"POLYGON ((-112.0166015625 45.966796875, -112.0..."
dpnr6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"POLYGON ((-81.0791015625 40.6494140625, -81.07..."

In [38]:
OVERWRITE = False

geohash_geojson_filename = '../data/188-million-us-wildfires/geohash_{}_count_by_year.geojson'.format(geohash_analysis_precision)
if not os.path.exists(geohash_geojson_filename) or OVERWRITE:
    geohash_gdf.to_file(geohash_geojson_filename, driver="GeoJSON")

In [ ]:
s3_destination_bucket = 'fire-map'
prefix = 'geohash_{}_count_by_year'.format(geohash_analysis_precision)
!mapbox-tile-copy {geohash_geojson_filename} s3://{s3_destination_bucket}/{prefix}/{z}/{x}/{y}

## Map Visualization

### Generate Colors for STAT_CAUSE_CODE

Let's dig into the causes of fires a bit more. First, we'll list out all of the possible values.

To save space in our vector tiles, we'll include the Cause Code rather than the Cause Description. To display human readable names, let's build a quick mapping and print it to json for inclusion in our JS.

In [ ]:
cause_desc_counts = gdf \
    .groupby(['STAT_CAUSE_DESCR', 'STAT_CAUSE_CODE']) \
    .size()\
    .reset_index()\
    .rename(columns={0:"n_occurances"})\
    .sort_values(['n_occurances'], ascending=False)\
    .reset_index(drop=True)
cause_desc_counts['STAT_CAUSE_CODE'] = cause_desc_counts['STAT_CAUSE_CODE'].astype(int)

def assign_color(row):
    try:
        return palettable.matplotlib.Inferno_13.hex_colors[row.name]
    except IndexError:
        return '#ff0000'
    
cause_desc_counts['color'] = cause_desc_counts.apply(assign_color, axis=1)
display(cause_desc_counts)
cause_desc_counts.to_json(orient='records')

Reference: https://gis.stackexchange.com/questions/148834/creating-a-really-large-shapefile-without-eating-all-the-virtual-memory

### Point Data to GeoJSON

Dump out our GeoDataFrame to GeoJSON. This one takes a while and doesn't provide much feedback while it's in progress. In my experience, the output file is just over 1000MB -- you can keep an eye on the size of that file to check progress.

In [ ]:
geojson_filename = '../data/188-million-us-wildfires/FPA_FOD_20170508.geojson'

if not os.path.exists(geojson_filename):
    gdf.to_file(geojson_filename, driver="GeoJSON")

### Tile Generation and Upload

#### STAT_CAUSE_CODE

Reference: https://github.com/mapbox/tippecanoe

`tippecanoe -o FPA_FOD_20170508.mbtiles -f -Z1 -z20 -y DISCOVERY_DATE,CONT_DATE,FIRE_SIZE_CLASS,STAT_CAUSE_CODE --drop-densest-as-needed FPA_FOD_20170508.geojson`

In [ ]:
mbtiles_filename = '../data/188-million-us-wildfires/FPA_FOD_20170508.mbtiles'

if not os.path.exists(mbtiles_filename):
    !tippecanoe -o {mbtiles_filename} -ae -D 18 -d 18 -m 10 -rg -y DFIRE_YEAR -y STAT_CAUSE_CODE -y FIRE_YEAR -y FIRE_NAME -L fires:{geojson_filename}

Reference: https://github.com/mapbox/mapbox-sdk-py https://www.mapbox.com/api-documentation/#uploads

Use `mapbox-geostats` to query the resulting mbtiles file. Review the results to ensure that

In [ ]:
!mapbox-geostats {mbtiles_filename}

Use `mapbox-tile-copy` to move our tiles up to an S3 bucket. Don't forget to 1) allow public access to the bucket's keys., 2) setup static site hosting, and 3) enable CORS requests.

In [ ]:
!mapbox-tile-copy {mbtiles_filename} s3://{s3_destination_bucket}/{z}/{x}/{y}